# Generated by Django 5.1.2 on 2026-01-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='タグ名（例: 肩こり解消, ストレス軽減）', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercisemenu',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='この運動メニューに関連するタグ', to='condition_manager.tag'),
        ),
    ]
