# Generated by Django 6.0.1 on 2026-01-31 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_manager', '0002_tag_exercisemenu_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionlog',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
