# Generated by Django 6.0.1 on 2026-02-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_manager', '0003_alter_conditionlog_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='view_count',
            field=models.IntegerField(default=0, help_text='このルーティンの閲覧回数'),
        ),
    ]
